#!/usr/bin/env bash
cd /jetty-home
java -Xmx4096m \
  -Dsolr.solr.home=/solr-home \
  -Djava.util.logging.config.file=/jetty-home/etc/solr-logging.properties \
  -Djetty.port=$PORT \
  -jar start.jar

