#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PORT="${PORT:-8181}"
cd ${DIR}/jetty-home
exec java -Xmx${JAVA_HEAP:-32g} \
  -Dsolr.solr.home=${DIR}/solr-home \
  -Djava.util.logging.config.file=${DIR}/jetty-home/etc/solr-logging.properties \
  -Djetty.port=$PORT \
  -jar start.jar
